Update Viya_Manager.yml

diff --git a/.github/workflows/Viya_Manager.yml b/.github/workflows/Viya_Manager.yml
--- a/.github/workflows/Viya_Manager.yml
+++ b/.github/workflows/Viya_Manager.yml
@@ -13,6 +13,15 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
+      - name: Check target folder
+        run: |
+          if [ ! -d /Users/mauro.cazzari/Downloads ]; then
+            echo "Target folder not found."
+          else
+            echo "Target folder found."
+            exit 1
+          fi
+
       - name: Download New CSV
         run: |
           if curl -o /Users/mauro.cazzari/Downloads/README.md https://github.com/sassoftware/iot-manage-viya-4-cloud-environments-with-viya_manager/blob/main/README.md; then
