Update Viya_Manager.yml

diff --git a/.github/workflows/Viya_Manager.yml b/.github/workflows/Viya_Manager.yml
--- a/.github/workflows/Viya_Manager.yml
+++ b/.github/workflows/Viya_Manager.yml
@@ -1,31 +1,74 @@
-# This is a basic workflow to help you get started with Actions
+name: Daily CSV Update
 
-name: Viya_Manager
-
-# Controls when the workflow will run
 on:
+#  schedule:
+#    - cron: '0 8 * * *' # Runs every day at midnight (UTC)
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  configurator:
-    runs-on: ${{ matrix.config.os }}
-    strategy:
-      matrix:
-        config:
-        - {os: "ubuntu-latest", url: "https://github.com/sassoftware/iot-manage-viya-4-cloud-environments-with-viya_manager/blob/main/README.md", name: "Viya_Manager", pathInArchive: "/tmp" }
-#        - {os: "ubuntu-latest", url: "https://github.com/sassoftware/iot-manage-viya-4-cloud-environments-with-viya_manager/blob/main/Code/Viya_Manager.tar.gz", name: "Viya_Manager", pathInArchive: "/tmp" }
-#        - {os: "windows-latest", url: "https://get.helm.sh/helm-v3.0.0-beta.3-windows-amd64.zip", name: "hb3.exe", pathInArchive: "windows-amd64/helm.exe" }
+  download-csv:
+    runs-on: ubuntu-latest
+
     steps:
-      - uses: engineerd/configurator@v0.0.1
-        with:
-          name: ${{ matrix.config.name }}
-          url: ${{ matrix.config.url }}
-          pathInArchive: ${{ matrix.config.pathInArchive }}
-      - name: Testing
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Download New CSV
         run: |
-          Viya_Manager --helpset of commands using the runners shell
-      - name: Run a multi-line script
+          if curl -o /tmp/README.md https://github.com/sassoftware/iot-manage-viya-4-cloud-environments-with-viya_manager/blob/main/README.md; then
+            echo "CSV download successful."
+          else
+            echo "CSV download failed."
+            exit 1
+          fi
+
+      - name: Check CSV File Size
+        id: check-csv
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if [ -s /tmp/README.md ]; then
+            echo "CSV file is not empty."
+          else
+            echo "CSV file is empty."
+            exit 1
+          fi
+          
+      # - name: Check for Differences
+      #   id: check-differences
+      #   run: |
+      #     if ! diff -q data/new-data.csv data/childcare_locations.csv; then
+      #       echo "CSV files are different."
+      #       echo "DIFFERENT_CSV=true" >> $GITHUB_ENV
+      #     else
+      #       echo "CSV files are the same. Skipping commit."
+      #       echo "DIFFERENT_CSV=false" >> $GITHUB_ENV
+      #     fi
+
+      # - name: Overwrite CSV
+      #   if: steps.check-csv.outcome == 'success' && env.DIFFERENT_CSV == 'true'
+      #   run: |
+      #     mv data/new-data.csv data/childcare_locations.csv
+
+      # - name: Commit and Push Changes
+      #   if: steps.check-csv.outcome == 'success' && env.DIFFERENT_CSV == 'true'
+      #   run: |
+      #     git config --global user.name "GitHub Actions"
+      #     git config --global user.email "actions@github.com"
+          
+      #     timestamp=$(date +'%Y%m%d%H%M%S')
+      #     branch_name="update-csv-$timestamp"
+
+      #     git checkout -b "$branch_name"
+
+      #     git add data/childcare_locations.csv
+
+      #     git commit -m "Update CSV file"
+
+      #     git push origin "$branch_name"
+
+      #     git checkout main
+      #     git merge --no-ff "$branch_name"
+      #     git push origin main
+
+      #     # delete the temporary branch
+      #     git branch -d "$branch_name"
+      #     git push origin --delete "$branch_name"
